version: "3.9"
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:3000"
    restart: always
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app